kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: objectmirror
rules:
- apiGroups:
  - "veccsolutions.com"
  resources:
  - "sharedsecrets"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: objectmirror-binding-others
subjects:
- kind: ServiceAccount
  name: objectmirror
  namespace: vecc-objectmirror
roleRef:
 kind: ClusterRole
 name: objectmirror
 apiGroup: rbac.authorization.k8s.io